### PR TITLE
404 Not Found | Joe Gates

### PR DESCRIPTION
**Pull request by jbg2023**
## Comfortability

3. Can complete it, but don't fully understand it.

## Completion

3. Completed all mvp tasks

## Additional Comments

***Functions in prompt 12 & 13 didn't work when I tested the output in browser, but seemed to work when I tried with just the loops outside of the function with 'node main.js' in the console. Not sure what I was doing wrong there.
Screen Shot 2022-11-02 at 10 23 31 PM

### CODE REVIEW

**Comment by jbg2023** [comment]
***** Line 285 I must of uncommented by mistake, which threw off the functions.

**Comment by jbg2023** [comment]
Also, I misread prompt 2 is asking for even numbers only! it should have been "function prompt2() {
  for (let i = 2; i < 100; i+=2) {
    console.log(i);
  }
}"

**Comment by jbg2023** [comment]
Also, I should have left the function calls uncommented for y'all. My bad.

**Comment by sarahrosehumenik** [comment]
Joe wonderful job! There is one prompt that returned the incorrect answer- we ask that 80% of the lab is complete/correct so this lab is marked as completed! 

//for prompt11 the number it returned is 12 but the answer is 15!

**Pull request closed without merging**
